defmodule Uderzo.Bindings do
  # AUTOGENERATED. DO NOT TOUCH!!
  alias Uderzo.GraphicsServer
  def comment(comment), do: comment(GraphicsServer, comment)
  def comment(pid,comment), do: GraphicsServer.send_commands(pid, [{:comment, comment}])
  def window(height,width,title), do: window(GraphicsServer, height,width,title)
  def window(pid,height,width,title), do: GraphicsServer.send_commands(pid, [{:window, height,width,title}])
  def on_frame(frame_pid), do: on_frame(GraphicsServer, frame_pid)
  def on_frame(pid,frame_pid), do: GraphicsServer.send_commands(pid, [{:on_frame, frame_pid}])
end
