version: '2'
services:
  kafka:
    image: cdegroot/kafka:04a3654
    ports:
      - '9092:9092'
      - '2182:2181'
    environment:
      KAFKA_CREATE_TOPICS: "scheduler_journal:2:1:compact,scheduler:2:1"
