version: 2
jobs:
  build:
    working_directory: ~/palapa
    docker:
      - image: elixir:1.6.5
      - image: cdegroot/kafka:143a272
        environment:
          KAFKA_CREATE_TOPICS: "scheduler:2:1,scheduler_journal:2:1"
    steps:
      - restore_cache:
        keys:
          - asdf
      - checkout
      - run: make
      - save_cache:
        key: asdf
        paths:
          - ".asdf"

