version: 2
jobs:
  build:
    working_directory: ~/palapa
    docker:
      - image: cdegroot/palapa-ci:3cb8f5c
      - image: cdegroot/kafka:143a272
        environment:
          KAFKA_CREATE_TOPICS: "scheduler:2:1,scheduler_journal:2:1"
    steps:
      - checkout
      - run: source ~/.asdf/asdf.sh && make setup
      - save_cache:
          key: asdf
          paths:
            - "~/.asdf"
      - run: source ~/.asdf/asdf.sh && make deps test
