version: 2
jobs:
  build:
    working_directory: ~/palapa
    docker:
      - image: cdegroot/palapa-ci:7a44a89
      - image: cdegroot/kafka:143a272
        environment:
          KAFKA_CREATE_TOPICS: "scheduler:2:1,scheduler_journal:2:1"
    steps:
      - restore_cache:
        keys:
          - asdf
      - checkout
      - run:
          - git clone git@github.com:asdf-vm/asdf.git ~/.asdf --branch 0.4.3
          - source ~/.asdf/asdf.sh && make
      - save_cache:
        key: asdf
        paths:
          - ".asdf"
