// -*- mode: c; -*-
#include <stdio.h>
// OpenGL ES 3 should support the widest array of devices. One
// clear target is RPi with a framebuffer-to-gpio-display mirror.
#define GLFW_INCLUDE_ES3
#define GLFW_INCLUDE_GLEXT
#include <GLFW/glfw3.h>
#include <nanovg.h>
#define NANOVG_GLES3_IMPLEMENTATION
#include <nanovg_gl.h>
#include <nanovg_gl_utils.h>

#include "uderzo_io.h"

// Comment-driven development.
// [x] 1. Library initialization is done at program startup time.
// [x] 1a.For now, there's one global (vg/gl) context.
// [x] 2. Everything else is manual.
// [x] 3. For now, we openly admit to using nanovg, glfw, opengl es
// [x] 3a.So we directly map functions on the protocol, no translation
// [x] 3b.This should make code generation simpler, eventually
// [x] 3c.We also don't wrap pointers. They're just opaque handles on
//        the BEAM side.
// [x] 4. The render loop is BEAM-side, this code is passive
// [ ] 5. Any GLFW keyboard and mouse events are sent to stdout, async
// [ ] 6. Hence, the stdin/stdout protocol needs to be async
// [ ] 7. Mouse state can also be polled
// [ ] 8. BEAM-side, there should be a concept of flushing so that we
//        can batch commands. This is not visible here.

extern void errorcb(int error, const char *desc);
//extern void key_callback(GLFWwindow *window, int key, int scancode, int action, int mods);
extern void read_loop();

// These pesky global things, for now.
NVGcontext* vg = NULL;
//erlang_pid key_callback_pid; // etcetera for all the GLFW callbacks

int main() {
    if (!glfwInit()) {
        SEND_ERLANG_ERR("Failed to init GLFW.");
        return -1;
    }

    glfwSetErrorCallback(errorcb);

    glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);

    fprintf(stderr, "Uderzo graphics executable started up.\n");

    read_loop();
}

// TODO: read_loop and command handling/dispatch should be moved to a clixir_support.c file, probably
// merged with the uderzo_io stuff. It should be completely standard for any Clixir binding. 

extern void handle_command(const char *command, unsigned short len);


void read_loop() {
    // Protocol: 2 bytes with big endian length, then the actual command.
    // So maximum size we can read is 65535. We're not even gonna allocate
    // that with today's stack sizes and a single process. Once we start pushing
    // large graphics objects like bitmaps through the pipe, we'll regret the
    // decision but maybe by then we have converted this to a full C node.
    char buffer[BUF_SIZE];
    unsigned char size_buffer[2];

    while (1) { // TODO how do we end the fun?
        assert(read(STDIN_FILENO, size_buffer, 2) == 2);
        unsigned short size = (size_buffer[0] << 8) + size_buffer[1];

        unsigned short bytes_read = read(STDIN_FILENO, buffer, size);
        if (bytes_read < 0) {
            fprintf(stderr, "Error, read %d bytes, expected positive number\n", bytes_read);
            exit(-1);
        } else if (bytes_read < size) {
            fprintf(stderr, "Error, short read. Expected %d, got %d\n", size, bytes_read);
            dump_hex(buffer, bytes_read);
            exit(-1);
        } else {
            fprintf(stderr, "Handling command of %d bytes, size %d:\n", bytes_read, size);
            dump_hex(buffer, size);
            handle_command(buffer, size);
        }
    }
}

// _dispatch_command will be generated by Clixir, this is its signature:
static void _dispatch_command(const char *buf, unsigned short len, int *index);

static void _handle_command(const char *command, unsigned short len, int *index) {
    // For now, we parse the command, then echo it back.
    // Note that all we accept for now is
    //   {cast, <<function_name>>, args.... [, callback_pid]}
    // Or, preferably, an array of these.
    ei_term term;

    if (*index >= len) {
        fprintf(stderr, "decode done\n");
        return;
    }

    int result = ei_decode_ei_term(command, index, &term);
    fprintf(stderr, "Got result %d index is now 0x%x\n", result, *index);
    assert(result == 1);
    fprintf(stderr, "Got term type %c / %d\n", term.ei_type, term.ei_type);
    switch (term.ei_type) {
    case ERL_SMALL_TUPLE_EXT:
        _dispatch_command(command, len, index);
        _handle_command(command, len, index);
        break;
    case ERL_LIST_EXT:
        // A list of commands; we can send this for efficiency. Loop and go.
        fprintf(stderr, "Handling list is arity %d\n", term.arity);
        for (int i = 0; i < term.arity; i++) {
            _handle_command(command, len, index);
        }
        break;
    case ERL_NIL_EXT:
        fprintf(stderr, "Skip nil\n");
        break;
    default:
        fprintf(stderr, "Unknown term type %c / %d\n", term.ei_type, term.ei_type);
        assert(1 == 0);
    }
}
void handle_command(const char *command, unsigned short len) {
  int index = 1;
  _handle_command(command, len, &index); // Skip version number
}

void errorcb(int error, const char *desc) {
    // TODO proper callback on stdout as well.
    fprintf(stderr, "GLFW error %d: %s\n", error, desc);
    // For now, just crash.
    assert(0);
}

// End of manually maintained header. Generated code follows below.
